name: Hello World Cron Job

on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo 'Hello World!'

